name: swiftdrop
description: A multi-role delivery app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
    
    
  fl_chart: ^1.2.0


  url_launcher: ^6.3.0

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.7.20

  # Google Sign In
  google_sign_in: ^6.2.1

  # Google Maps
  google_maps_flutter: ^2.5.3

  # HTTP & API
  dio: ^5.4.3
  retrofit: ^4.1.0
  http: ^1.2.1

  # Local storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0

  # UI
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.4
  lottie: ^3.1.0
  iconsax: ^0.0.8
  badges: ^3.1.2

  # Utils
  intl: ^0.19.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  uuid: ^4.3.3
  flutter_dotenv: ^5.1.0
  path: ^1.9.0
  mime: ^1.0.5

  # Image picking and uploading
  image_picker: ^1.0.7
  cloudinary_public: ^0.23.1

  # Real-time
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.3.11
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env