// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFA4Fwgb_QMQYvGdYQnrtYkiI-mjlyoY4',
    appId: '1:580367930936:ios:f8d6e47f27b733f1dd78cd',
    messagingSenderId: '580367930936',
    projectId: 'swiftdrop-92561',
    storageBucket: 'swiftdrop-92561.firebasestorage.app',
    iosClientId: '580367930936-cqk1j5io264gcdahnvujsnodst3oqe9u.apps.googleusercontent.com',
    iosBundleId: 'com.swiftdrop.swiftdrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFA4Fwgb_QMQYvGdYQnrtYkiI-mjlyoY4',
    appId: '1:580367930936:ios:f8d6e47f27b733f1dd78cd',
    messagingSenderId: '580367930936',
    projectId: 'swiftdrop-92561',
    storageBucket: 'swiftdrop-92561.firebasestorage.app',
    iosClientId: '580367930936-cqk1j5io264gcdahnvujsnodst3oqe9u.apps.googleusercontent.com',
    iosBundleId: 'com.swiftdrop.swiftdrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpJYa06KJRQbxH77NYYYqIG9AUtobPY0E',
    appId: '1:580367930936:web:97102bb2de653f7cdd78cd',
    messagingSenderId: '580367930936',
    projectId: 'swiftdrop-92561',
    authDomain: 'swiftdrop-92561.firebaseapp.com',
    storageBucket: 'swiftdrop-92561.firebasestorage.app',
    measurementId: 'G-5ZGPHV7889',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpJYa06KJRQbxH77NYYYqIG9AUtobPY0E',
    appId: '1:580367930936:web:97102bb2de653f7cdd78cd',
    messagingSenderId: '580367930936',
    projectId: 'swiftdrop-92561',
    authDomain: 'swiftdrop-92561.firebaseapp.com',
    storageBucket: 'swiftdrop-92561.firebasestorage.app',
    measurementId: 'G-5ZGPHV7889',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvlAljySqtzRmJzdPDGSeJ983NVy_5byw',
    appId: '1:580367930936:android:32a2b3663d63c9c7dd78cd',
    messagingSenderId: '580367930936',
    projectId: 'swiftdrop-92561',
    storageBucket: 'swiftdrop-92561.firebasestorage.app',
  );

}